<a href="https://colab.research.google.com/github/samalasathwika/Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Return only values greater than 10, then replace every value below 8 with 0.
import numpy as np
a=np.array([12, 5, 8, 19, 3, 15, 7, 22, 10, 6])

b=a[a>10]
print ("elemets greater than 10 are",b)
a[a<8]=0
print("new array after replacing",a)


elemets greater than 10 are [12 19 15 22]
new array after replacing [12  0  8 19  0 15  0 22 10  0]


In [44]:
#reshape it into a 4 × 6 matrix. Extract the first two rows, last three columns, and the element at row 3, column 4.
arr=np.arange(1,25)

a=arr.reshape((4,6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [22]:
b=a[:2,-3:]
b

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12]])

In [24]:
c=a[3,4]
c

np.int64(23)

marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [92, 88, 95],
    [55, 60, 58]
])

Find each student’s average, each subject’s average, the student with the highest total marks, and all students whose average is above 80.

In [30]:
marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [92, 88, 95],
    [55, 60, 58]
])
stu1=marks[0].mean()
stu2=marks[1].mean()
stu3=marks[2].mean()
stu4=marks[3].mean()
print("Student 1 subjects avg is ",stu1)
print("Student 2 subjects avg is ",stu2)
print("Student 3 subjects avg is ",stu3)
print("Student 4 subjects avg is ",stu4)

sub1=marks[:,0].mean()
sub2=marks[:,1].mean()
sub3=marks[:,2].mean()

print("Subject 1 avg is ",sub1)
print("Subject 2 avg is ",sub2)
print("Subject 3 avg is ",sub3)

total1=marks[0].sum()
total2=marks[1].sum()
total3=marks[2].sum()
total4=marks[3].sum()

print("Total marks of student 1 is ",total1)
print("Total marks of student 2 is ",total2)
print("Total marks of student 3 is ",total3)
print("Total marks of student 4 is ",total4)




Student 1 subjects avg is  84.33333333333333
Student 2 subjects avg is  69.0
Student 3 subjects avg is  91.66666666666667
Student 4 subjects avg is  57.666666666666664
Subject 1 avg is  72.5
Subject 2 avg is  75.75
Subject 3 avg is  78.75
Total marks of student 1 is  253
Total marks of student 2 is  207
Total marks of student 3 is  275
Total marks of student 4 is  173


In [31]:
student_averages = marks.mean(axis=1)
print("Student averages:", student_averages)

students_above_80_avg = np.where(student_averages > 80)[0]

if len(students_above_80_avg) > 0:
    print("Students with average marks above 80:")
    for student_index in students_above_80_avg:
        print(f"  Student {student_index + 1} (Average: {student_averages[student_index]:.2f})")
else:
    print("No students found with average marks above 80.")

Student averages: [84.33333333 69.         91.66666667 57.66666667]
Students with average marks above 80:
  Student 1 (Average: 84.33)
  Student 3 (Average: 91.67)


Normalize this array to the range 0–1:
arr = np.array([10, 20, 30, 40, 50])

Use the min-max normalization formula. Don’t hardcode the minimum or maximum.

In [34]:
arr = np.array([10, 20, 30, 40, 50])
min_val=arr.min()
max_value=arr.max()
normalization = (arr-min_val)/(max_value-min_val)
print("Normalized array ", normalization)

Normalized array  [0.   0.25 0.5  0.75 1.  ]



sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [120, 180, 160],
    [500, 450, 550]
])

Find total sales per row, total sales per column, the row with the highest total sales, and replace values below the overall mean with 0.

In [42]:
sales = np.array([
    [100, 200, 150],
    [300, 250, 400],
    [120, 180, 160],
    [500, 450, 550]
])



row_sum1=sales[0].sum()
row_sum2=sales[1].sum()
row_sum3=sales[2].sum()
row_sum4=sales[3].sum()

col_total1=sales[:,0].sum()
col_total2=sales[:,1].sum()
col_total3=sales[:,2].sum()

print("Total sales for row 1 is ",row_sum1)
print("Total sales for row 2 is ",row_sum2)
print("Total sales for row 3 is ",row_sum3)
print("Total sales for row 4 is ",row_sum4)

print("Total sales for column 1 is ",col_total1)
print("Total sales for column 2 is ",col_total2)
print("Total sales for column 3 is ",col_total3)

overall_mean=sales.mean()
print(overall_mean)

sales[sales<overall_mean]=0
print("midified sales data ",sales)



Total sales for row 1 is  450
Total sales for row 2 is  950
Total sales for row 3 is  460
Total sales for row 4 is  1500
Total sales for column 1 is  1020
Total sales for column 2 is  1080
Total sales for column 3 is  1260
280.0
midified sales data  [[  0   0   0]
 [300   0 400]
 [  0   0   0]
 [500 450 550]]
